name: Continuous Integration

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      # update cache version if change in version in requirement files
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-cache-v02-${{ hashFiles('setup.cfg') }}-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-cache-v02-
    - name: Install basic libraries
      run: |
        python -m venv ./.venv && . ./.venv/bin/activate && python -m pip install --upgrade pip==22.2 &&
        pip install setuptools==50.3.2 wheel==0.36.2 && pip install -r requirements-dev.txt
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: flake8
      run: |
        . ./.venv/bin/activate && flake8 transforms tests
    - name: black
      run: |
        . ./.venv/bin/activate && black -l 120 --check transforms tests
    - name: Install library with all dependencies
      run: |
        . ./.venv/bin/activate &&
        python -m pip install --upgrade pip==22.2 && pip install -e . && pip install git+https://github.com/kbressem/trainlib.git#egg=trainlib
    - name: Unit tests
      run: |
        . ./.venv/bin/activate && pip install pytest==6.2.5 && pytest
